SELECT text_to_semver('1.2.3') < text_to_semver('1.2.2'); -- FALSE
SELECT text_to_semver('1.2.3') < text_to_semver('1.2.3'); -- FALSE
SELECT text_to_semver('1.2.3') < text_to_semver('1.2.4'); -- TRUE
SELECT text_to_semver('1.2.3') < text_to_semver('1.2.3-beta'); -- FALSE
SELECT text_to_semver('1.0.0-alpha') < text_to_semver('1.0.0-alpha.1'); -- TRUE
SELECT text_to_semver('1.0.0-alpha.1') < text_to_semver('1.0.0-alpha.beta'); -- TRUE
SELECT text_to_semver('1.0.0-alpha.beta') < text_to_semver('1.0.0-beta'); -- TRUE
SELECT text_to_semver('1.0.0-beta') < text_to_semver('1.0.0-beta.2'); -- TRUE
SELECT text_to_semver('1.0.0-beta.2') < text_to_semver('1.0.0-beta.11'); -- TRUE
SELECT text_to_semver('1.0.0-beta.11') < text_to_semver('1.0.0-rc.1'); -- TRUE
SELECT text_to_semver('1.0.0-rc.1') < text_to_semver('1.0.0'); -- TRUE
SELECT text_to_semver('1.0.0') < text_to_semver('1.0.1'); -- TRUE
SELECT text_to_semver('1.0.0-alpha.1.b.2') < text_to_semver('1.0.0-alpha.1.b.2'); -- FALSE
SELECT text_to_semver('1.0.0-alpha.1.b.2') < text_to_semver('1.0.0-alpha.1.b.3'); -- TRUE
SELECT text_to_semver('1.0.0-alpha.1.b') < text_to_semver('1.0.0-alpha.1.b.3'); -- TRUE
